### ISSUE TITLE
Cannot add github access-token

### ISSUE THREAD

**Issue by aesnyder** [circle-cli/circle-cli#2]
```
dyld: lazy symbol binding failed: Symbol not found: _SSL_load_error_strings
  Referenced from: /Users/aaronellissnyder/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rugged-0.22.2/lib/rugged/rugged.bundle
  Expected in: flat namespace
```

When trying to add github-token...

Fixed by `gem install rugged --pre`

https://github.com/libgit2/rugged/issues/475

**Comment by byroot** [comment]
It's because you probably updated libgit2 since you installed the gem.

**Comment by aesnyder** [comment]
I don't think so, this was a fresh install today. Like I said `gem install rugged --pre` fixed it.
