### ISSUE TITLE
The CLI does not support the Bitbucket Beta

### ISSUE THREAD

**Issue by jpoutrin** [circle-cli/circle-cli#20]
Hi Guys,
I know you guys are still in beta regarding bitbucket.
here is what you get when using the CLI

```
$ circle
Unsupported repo url format git@bitbucket.org:mybucket.git
```

if you can get some time to add support for it. 

Cheers

**Comment by codeurge** [comment]
Sorry I've been a bit absent from working on this project lately. I'll try to get around to working on this sometime this week. I'll update this issue when a release has been tagged and pushed to RubyGems.

**Comment by rdark** [comment]
https://github.com/martinemde/gitable/pull/1

**Comment by NomiJ** [comment]
Is there any update on this? From @rdark link it seems to be fixed in gitable , yet the hard coded limitation exists 👎 
>>         abort! "Unsupported repo url format #{repo.uri}" unless repo.uri.github?

**Comment by manu29d** [comment]
Shouldn't the burden of parsing the URI and raising errors be offloaded to `Gitable::URI.parse`?

**Comment by nassendelft** [comment]
Any news on this?
I'm getting **is not a git repository** message trying to use the tool on bitbucket repo

**Comment by NickDickinsonWilde** [comment]
@manu29d It is - the problem was that gitable didn't support bitbucket and then this needed a new version spec
