### ISSUE TITLE
CLI doesn't support spaces in path

### ISSUE THREAD

**Issue by lougreenwood** [circle-cli/circle-cli#28]
It seems that the Circle CI CLI tool doesn't support a path which contains spaces, it results in the following error:

```
./circleci_build
Receiving latest version of circleci...
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

This seems to be because the CLI tool doesn't wrap `$PWD` in quotation marks.

Moving the project to a path with no spaces fixes the error, but a long term, it would be better if Cli just supported paths with spaces.

**Comment by rzane** [comment]
I think you're reporting an issue to the wrong place. This isn't the official Circle CI command line tool.

**Comment by lougreenwood** [comment]
oops, thanks - sorry! 🤒
