### ISSUE TITLE
Bug: Undefined method `gsub' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by mhartington** [circle-cli/circle-cli#5]
Getting this error when I try to invoke `circle` from the cli

```
/Library/Ruby/Gems/2.0.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:29:in `dispatch!': undefined method `gsub' for nil:NilClass (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:13:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/circle-cli-0.0.1/bin/circle:9:in `<top (required)>'
        from /usr/bin/circle:23:in `load'
        from /usr/bin/circle:23:in `<main>'
```

OSX Yosemite
Ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by byroot** [comment]
Lol. It doesn't support not providing a subcommand it seems.

TBH I'm not using this anymore, so if someone else want to maintain it I can transfer the ownership.

**Comment by byroot** [comment]
cc @aesnyder maybe you are interested in taking ownership of this project?

**Comment by mhartington** [comment]
All good :+1:
