### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by benbuckman** [circle-cli/circle-cli#6]
Running `circle` by itself, I would expect it to output usage info, but instead I get:

```
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:29:in `dispatch!': undefined method `gsub' for nil:NilClass (NoMethodError)
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:13:in `run'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/bin/circle:9:in `<top (required)>'
    from /opt/boxen/rbenv/versions/2.1.2/bin/circle:23:in `load'
    from /opt/boxen/rbenv/versions/2.1.2/bin/circle:23:in `<main>'
```

After adding tokens, running `circle status`, I get:

```
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:86:in `github_repo': undefined method `inpect' for "https://github.com/Shyp/shyp_api":String (NoMethodError)
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:77:in `last_status'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:38:in `run_status'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:31:in `dispatch!'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/lib/circle/cli.rb:13:in `run'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/circle-cli-0.0.1/bin/circle:9:in `<top (required)>'
    from /opt/boxen/rbenv/versions/2.1.2/bin/circle:23:in `load'
    from /opt/boxen/rbenv/versions/2.1.2/bin/circle:23:in `<main>'
```

**Comment by byroot** [comment]
Hi. I'm not using this gem anymore. However I'd be glad to merge a fix for this and even transfer ownership to whoever would like to maintain it.

**Comment by codeurge** [comment]
I opened a PR for this - and may be interested in taking over this gem if you're no longer maintaining it. Please e-mail me at derek@codeurge.com so we can arrange the transfer of ownership.

**Comment by byroot** [comment]
@codeurge I made you an owner fo the gem on rubygems.org, you can now publish new versions.

Also if you want me to transfer the repo ownership, just delete your fork and tell it here, I'll transfer it afterwards.

**Comment by codeurge** [comment]
@byroot Went ahead and deleted my fork. Feel free to transfer, and thanks for getting it done so quickly! I'm excited to do some updates and features on this gem I've been using a while - so thanks for everything else you've done so far as well. :+1:

**Comment by byroot** [comment]
welcome. Thanks for adopting that gem.
